name: Docker Image CI

on:
  push:
    tags: "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Git tag
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t  ${{ secrets.DOCKER_HUB_USERNAME }}/php8.3-fullstack:${{ env.TAG }} .
        working-directory: ./

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push  ${{ secrets.DOCKER_HUB_USERNAME }}/php8.3-fullstack:${{ env.TAG }}
        working-directory: ./
